// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJyNOPlNoQl3YZc7kFSGRMPKTyuM9Tr5k',
    appId: '1:754807946146:web:04a28762841fdf475d50fb',
    messagingSenderId: '754807946146',
    projectId: 'giycik-c4989',
    authDomain: 'giycik-c4989.firebaseapp.com',
    storageBucket: 'giycik-c4989.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIeA8-L4dlaI2UEgkpQv4TN-B284a1pvs',
    appId: '1:754807946146:android:387335e98f3121e15d50fb',
    messagingSenderId: '754807946146',
    projectId: 'giycik-c4989',
    storageBucket: 'giycik-c4989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHLamJ80KQAq63BT8KC8Vaz6obz4OStg',
    appId: '1:754807946146:ios:524b22c2b27680eb5d50fb',
    messagingSenderId: '754807946146',
    projectId: 'giycik-c4989',
    storageBucket: 'giycik-c4989.firebasestorage.app',
    iosBundleId: 'com.example.gircik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHLamJ80KQAq63BT8KC8Vaz6obz4OStg',
    appId: '1:754807946146:ios:524b22c2b27680eb5d50fb',
    messagingSenderId: '754807946146',
    projectId: 'giycik-c4989',
    storageBucket: 'giycik-c4989.firebasestorage.app',
    iosBundleId: 'com.example.gircik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJyNOPlNoQl3YZc7kFSGRMPKTyuM9Tr5k',
    appId: '1:754807946146:web:df6f6faf22de5de45d50fb',
    messagingSenderId: '754807946146',
    projectId: 'giycik-c4989',
    authDomain: 'giycik-c4989.firebaseapp.com',
    storageBucket: 'giycik-c4989.firebasestorage.app',
  );
}
