from typing import Optional
from pydantic import BaseModel
from datetime import datetime

# Shared properties
class ClothingItemBase(BaseModel):
    name: str
    category: str
    color: str
    image_url: Optional[str] = None

# Properties to receive on item creation
class ClothingItemCreate(ClothingItemBase):
    id: str # UUID generated by Flutter app

# Properties to receive on item update
class ClothingItemUpdate(BaseModel):
    name: Optional[str] = None
    category: Optional[str] = None
    color: Optional[str] = None
    usage_count: Optional[int] = None

# Properties shared by models stored in DB
class ClothingItemInDBBase(ClothingItemBase):
    id: str
    user_id: int
    usage_count: int
    created_at: datetime

    class Config:
        from_attributes = True

# Properties to return to client
class ClothingItem(ClothingItemInDBBase):
    pass
