from typing import Optional, List
from pydantic import BaseModel
from datetime import datetime

class OutfitItemDataBase(BaseModel):
    name: str
    icon_name: Optional[str] = None
    clothing_item_id: str

class OutfitItemDataCreate(OutfitItemDataBase):
    pass

class OutfitItemData(OutfitItemDataBase):
    id: int
    display_order: int

    class Config:
        from_attributes = True

# Shared properties
class OutfitBase(BaseModel):
    title: str
    style: str
    season: str
    is_favorite: bool = False

# Properties to receive on item creation
class OutfitCreate(OutfitBase):
    id: str # UUID generated by Flutter App
    items: List[OutfitItemDataCreate]

# Properties to receive on item update
class OutfitUpdate(BaseModel):
    title: Optional[str] = None
    style: Optional[str] = None
    season: Optional[str] = None
    is_favorite: Optional[bool] = None
    items: Optional[List[OutfitItemDataCreate]] = None

# Properties shared by models stored in DB
class OutfitInDBBase(OutfitBase):
    id: str
    user_id: int
    created_at: datetime

    class Config:
        from_attributes = True

# Properties to return to client
class Outfit(OutfitInDBBase):
    items: List[OutfitItemData] = []
